[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cyphex-backend"
version = "0.1.0"
description = "CYPHEX - Real-time Voice Integrity Verification Framework"
requires-python = ">=3.11"
authors = [
    {name = "CYPHEX Team"}
]
dependencies = [
    "fastapi",
    "uvicorn",
    "torch",
    "torchaudio",
    "librosa"
]
